### ISSUE TITLE
Must buttons aren't added Game to the MyMusts.

### ISSUE THREAD

**Issue by veledzimovich-iTechArt** [smnenko/game-web-site#20]
I logged as fresh superuser in testing. 
OS: MacOS

**Comment by smnenko** [comment]
Try to configure host:port in "static/js/base.js" file  with your host and port. May be it can solve issue

**Comment by smnenko** [comment]
Anf ofc refresh page resources with Cntrl (cmd) + F5

**Comment by veledzimovich-iTechArt** [comment]
Yes. If I change host it works. But I found better way 

`fetch(document.location.origin + url, {`
