### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by veledzimovich-iTechArt** [smnenko/game-web-site#23]
I get an 404 error when I try to login with wrong password. 

I suggest to use `from django.contrib import messages` to notify user about wrong login.
Maybe you have better solution, for example you can use `class LoginForm(AuthenticationForm):
`

**Comment by veledzimovich-iTechArt** [comment]
Using LoginForm(AuthenticationForm) I can make like this 
![Screen Shot 2021-07-17 at 12 55 46](https://user-images.githubusercontent.com/77264872/126033299-90d1a091-4dc7-4577-98b5-e8ab9102d964.jpg)

**Comment by smnenko** [comment]
Solved in PR #13

**Comment by veledzimovich-iTechArt** [comment]
👍
